/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <game.h>
#include <stdint.h>
#include <stdlib.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
	init_peripherals(); // sets pins for I/O
	GAME game = get_new_game();

	while(1) {
		switch (game.state) {
			case STATE_WAIT_START:
				wait_to_start();
				game.state = STATE_SEQUENCE;
				break;
			case STATE_SEQUENCE:
				display_sequence(&game);
				game.state = STATE_USER_ATTEMPT;
				break;
			case STATE_USER_ATTEMPT:
				user_attempt(&game);
				break;
			case STATE_GAME_OVER:
				game_over_animation();
				display_score(game.round - 1);
				game = get_new_game();
				break;
		}
	}
}
